## Better NPM â€“ PostgreSQL Setup
## Start: docker compose -f docker-compose.postgres.yml up -d
## Admin UI: http://localhost:81
## Default login: admin@example.com / changeme

services:
  app:
    image: "ghcr.io/snxrcs/better-npm:latest"
    restart: unless-stopped
    ports:
      - "80:80"     # Public HTTP Port
      - "443:443"   # Public HTTPS Port
      - "81:81"     # Admin Web Port
      # Add any other Stream port you want to expose
      # - "21:21"   # FTP
    environment:
      TZ: "Europe/Berlin"
      DB_POSTGRES_HOST: "db"
      DB_POSTGRES_PORT: "5432"
      DB_POSTGRES_USER: "npm"
      DB_POSTGRES_PASSWORD: "npmpass"
      DB_POSTGRES_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: "true"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: "postgres:17"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "npm"
      POSTGRES_PASSWORD: "npmpass"
      POSTGRES_DB: "npm"
    volumes:
      - ./postgresql:/var/lib/postgresql
